name: C++ Syntax & Build Check

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  check-syntax:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install Pybind11 Headers
      run: pip install pybind11

    - name: Configure CMake
      run: cmake -B build -DCMAKE_PREFIX_PATH="$(python -c 'import pybind11; print(pybind11.get_cmake_dir())')"

    - name: Check Syntax (Compile)
      run: cmake --build build
